/// Generated by https://quicktype.io
use serde::{Deserialize, Serialize};
extern crate serde_json;

#[derive(Debug, Serialize, Deserialize)]
pub struct Error {
    #[serde(rename = "message")]
    message: Option<String>,

    #[serde(rename = "type")]
    error_type: Option<String>,

    #[serde(rename = "code")]
    code: Option<i64>,

    #[serde(rename = "error_subcode")]
    error_subcode: Option<i64>,

    #[serde(rename = "fbtrace_id")]
    fbtrace_id: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct FacebookGroups {
    #[serde(rename = "data")]
    data: Option<Vec<GroupDatum>>,

    #[serde(rename = "paging")]
    paging: Option<Paging>,

    #[serde(rename = "error")]
    error: Option<Error>,
}
#[derive(Serialize, Deserialize)]
pub struct FacebookPages {
    #[serde(rename = "data")]
    data: Option<Vec<PageDatum>>,

    #[serde(rename = "paging")]
    paging: Option<Paging>,

    #[serde(rename = "error")]
    error: Option<Error>,
}

#[derive(Serialize, Deserialize)]
pub struct GroupDatum {
    #[serde(rename = "id")]
    id: String,

    #[serde(rename = "name")]
    name: String,

    #[serde(rename = "description")]
    description: Option<String>,

    #[serde(rename = "picture")]
    picture: Option<Picture>,
}
#[derive(Serialize, Deserialize)]
pub struct PageDatum {
    #[serde(rename = "id")]
    id: String,

    #[serde(rename = "page_token")]
    page_token: String,
}

#[derive(Serialize, Deserialize)]
pub struct Picture {
    #[serde(rename = "data")]
    data: Data,
}

#[derive(Serialize, Deserialize)]
pub struct Data {
    #[serde(rename = "height")]
    height: i64,

    #[serde(rename = "is_silhouette")]
    is_silhouette: bool,

    #[serde(rename = "url")]
    url: String,

    #[serde(rename = "width")]
    width: i64,
}

#[derive(Serialize, Deserialize)]
pub struct Paging {
    #[serde(rename = "cursors")]
    cursors: Cursors,

    #[serde(rename = "next")]
    next: Option<String>,

    #[serde(rename = "previous")]
    previous: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct Cursors {
    #[serde(rename = "before")]
    before: Option<String>,

    #[serde(rename = "after")]
    after: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct FeedResponse {
    #[serde(rename = "id")]
    id: Option<String>,

    #[serde(rename = "error")]
    error: Option<Error>,
}
