# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - release
      - main
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Get version
        id: get-version
        uses: battila7/get-version-action@v2

      - name: Simple Git Version
        uses: jellydn/git-version@v2.5.5-1
        with:
          base-version: ${{ steps.get-version.outputs.version-without-v }}
