# .github/workflows/version.yml
name: Git Version

on:
  push:
    branches:
      - release
      - main
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'     # Providing patch-wording will override commits
                                            # defaulting to a patch bump.
          rc-wording:     'RELEASE,alpha'

  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history

      - name: Get version
        id: get-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Simple Git Version
        uses: jellydn/git-version@v2.5.5-1
        with:
          base-version: ${{ steps.get-version.outputs.current-version }}
